### ISSUE TITLE
Homework Week 7

### ISSUE THREAD

**Issue by ptums** [JacobDeming/DoNotGetMeStarted#2]
Hey Jacob I read through your issues and I'm going to discuss this with Ahmed and Faisal. This is a bit complex.

**Comment by JacobDeming** [comment]
Yeah, the bugs are a bit complex, but I am still working through them.
This game is only really in its "Alpha" state at the moment anyway, so I knew that there would still be some scattered bugs when I posted it. All in all it works pretty well though and is ready for testing.

**Comment by faisalrcb** [comment]
I took a look, and I think this will take more than one night to go through and break down. Overall it works great as your first attempt. We'll have go through it issue by issue over some time and work it out.
